### ISSUE TITLE
Jenkins login

### ISSUE THREAD

**Issue by Avec112** [camiloribeiro/cdeasy#12]
Hi.

> It is all set!
> Go to your local docker host port 8080 and past the token to start

I do not understand the "past the token" part. 
I am shown the Jenkins login page and it requires username and password it seems.

Am I doing something wrong?

**Comment by camiloribeiro** [comment]
Did you pull it recently? I remember a older version of jenkins docker image had this requirement, but it is not the case anymore. I also tried to download all over again and it seems fine. 

If you haven't pulled it recently, I suggest try removing the image:

```
    docker images | grep cdeasy_jenkins
```

It should give you the id of the image, so remove it:

```
   docker rmi <id_of_the_image>
```

then pull or clone again and run the commands once more. If you pulled it yesterday/today let me know. I will ask a friend to try and see if he/she has the same issue. Thanks.

**Comment by Avec112** [comment]
I pulled today and removed and pulled again.

**Comment by Avec112** [comment]
By the way I am on macOS.

**Comment by Avec112** [comment]
Sorry...my bad. I had two Jenkins instances running on two different machines at the same time. 
I was trying to access the one on my linux all the time while I should have accessed the url on my Mac.

**Comment by camiloribeiro** [comment]
:v No problem, have a great day. I hope it helps you.
