### ISSUE TITLE
build do seed quebrado

### ISSUE THREAD

**Issue by robsonbittencourt** [camiloribeiro/cdeasy#8]
O job seed está quebrando ao exevcutar do zero.

Tentei achar o erro, mas pela API o que você fez está certo...

Segue output

Processing DSL script example_alpha_pipeline.groovy
ERROR: (example_alpha_pipeline.groovy, line 3) No signature of method: javaposse.jobdsl.dsl.helpers.WorkflowDefinitionContext.cpsScm() is applicable for argument types: (example_alpha_pipeline$_run_closure1_closure2_closure3) values: [example_alpha_pipeline$_run_closure1_closure2_closure3@347255a6]
Possible solutions: cps(groovy.lang.Closure), inspect()
Notifying upstream projects of job completion
Finished: FAILURE

**Comment by camiloribeiro** [comment]
Olá @robsonbittencourt 

Eu acabei de baixar o repositório do zero em uma docker-machine vazia e buildei do inicio. Quando eu rodo o seed job ele funciona e o build status do travis também está positivo. Desculpe o inconveniente, mas tem como tentar um git pull so pra ter certeza que está na ultima versão e se estiver, tentar rm as images que tem desse projeto e tentar rodar de novo?

Obrigado.

**Comment by camiloribeiro** [comment]
Outro amigo rodou os testes localmente e tudo correu certo. Podemos fechar essa issue? obrigado @robsonbittencourt

**Comment by robsonbittencourt** [comment]
Posso fazer o teste a noite @camiloribeiro. Te dou um feedback e se for o caso já fechamos. 

O estranho é que a mensagem parece ser algo da job-dsl mesmo, só que a assinatura que ele diz que não existe, na verdade existe...

**Comment by camiloribeiro** [comment]
Obrigado @robsonbittencourt

**Comment by camiloribeiro** [comment]
ping

**Comment by robsonbittencourt** [comment]
Desculpe pela demora, não tinha conseguido ver antes.

Tinha até postado outro erro aqui antes, mas decidi apagar tudo e baixar novamente e funcionou :)

Valeu pela ajuda, e parabéns pelo projeto, me ajudou bastante.

**Comment by robsonbittencourt** [comment]
Provavelmente alguma configuração errada. Após reinstalar a imagem voltou a funcionar.

**Comment by camiloribeiro** [comment]
@robsonbittencourt valew!
